// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '01-cours'}],
  tp_FC: [{type: 'autogenerated', dirName: '02-tp_FC'}],
  autres: [{type: 'autogenerated', dirName: '03-autres'}],
};

module.exports = sidebars;
